### ISSUE TITLE
Unwanted text below site name and above course name

### ISSUE THREAD

**Issue by JosiahCarberry** [learningworks/moodle-block_enrolmenttimer#1]
The extract below from the html code of a moodle page occurs only when:
a) the plugin enrolment_timer ver 2016031700 is enabled (it is not there when the plugin is disabled)
b) the current user's role is not an admin role (at least, when the current user has the participant role)

It occurs only on the first page displayed after the user selects a course, but not on any other pages.
The date/time stamp shows the current local date/time, with the odd format of an am/pm format, but without either the "am" or "pm". 
I believe it also occurred in earlier versions of the plugin. 

It occurs with both Moodle 3.0 and 3.1.

The problem occurs when using a variety of different themes.

Here is the extract of the page. The extraneous code is immediately after the link to the favicon and immediately before the meta tag:
`<!DOCTYPE html>
<html  dir="ltr" lang="en" xml:lang="en">
<head>
    <title>Course: my course name</title>
    <link rel="shortcut icon" href="https://mysite.com/theme/image.php/more/theme/1465142948/favicon" />
    string(3) "6 2"
string(19) "2016-06-05 06:54:20"
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />`
etc.

The result of this extraneous code is the unwanted text appearing on the user's screen, immediately below the site name and above the course name.

**Comment by Chocolate-lightning** [comment]
Hello Josiah,

Could you please provide us with more information please? We believe it may be a conflict with another plugin and we have been unable to reproduce the issue. Upon review we do not interfere with the <HTML> global and do not print_object, var_dump and the echo's used have strings in front of them.

If you could provide us a list of additional plugins you have installed and if you have done any extra development to extend functionality.

Thanks.

**Comment by JosiahCarberry** [comment]
Hello,

My installation is pretty much plain vanilla with no changes to any installed files other than config.php, plus the addition of various plugins:

mod_certificate 3.0 (Build: 2015111601)
mod_questionnaire   3.1.0 (Build - 2016052000)
mod_videofile   1.06
block_enrolmenttimer    3.0.0
block_progress  Version for Moodle 2.0 onwards
qtype_ddmatch   1.6 
qtype_ordering  2016-05-11 (53)

I have additionally confirmed that the problem exists when all those additional plugins, other than enrolment timer, are disabled.

**Comment by Chocolate-lightning** [comment]
Hello,

We believe it may of been an issue with old code not getting updated as the version file was not bumped in the last commit. We have released a new version with a couple of tweaks in the lib file and you should be good to go.
