### ISSUE TITLE
Enhancement?

### ISSUE THREAD

**Issue by rbigras** [learningworks/moodle-block_enrolmenttimer#4]
Hi,
Last month, we installed the enrollment timer plugin on our platform and it is very exciting. Our students really appreciate it. However, it works only with ongoing courses when duration is defined in the enrollment key parameters. We would like to use the timer for other courses, those with no duration defined in the duration field because we want the course period to end at same moment for all students (at the date entered in the end date field). Do you think such an enhancement could be possible? (Could a checkbox be added in the parameters so we could choose to “activate” the timer for a specific course?)
Thank you!
Rosane

**Comment by Chocolate-lightning** [comment]
Hi Rosane,

I am glad that you have found the enrollment timer useful. 

We were discussing your feature request and were curious if you were using self enrollment as you can set a predefined end date on the method method rather than for each student enrollment.

Kind regards,

Matt

**Comment by rbigras** [comment]
Hi Matt,

Yes, we use self enrollment for all the courses, always with enrollment keys, each one being set for about one month (12 per year). For individual courses, depending on the contents, the duration is set for "1 week" or for "2 weeks". In these courses, a student benefits from a complete period of duration, no matter if he enrolls on the last day of the month. In these courses, the enrollment timer works perfectly.

But for other courses, those for with implication of an instructor (feedback, etc.) or with a forum, I cannot set a duration because the access has to end at the same moment for all students (at the end date set in the enrollment key). The student are informed of this end date, they do not really need the timer to tell them the remaining time, but they certainly would appreciate it (if the timer worked even without having a duration set, but it does not, the countdows seems to be based on the duration, not on the beginning and end dates). We believe the timer would help reduce procrastination in these courses. This is why I think that if there was a possibility, when a duration is not set, to "activate" the timer (to have it work with the dates instead of the duration), it would be great!

Regards,

Rosane

**Comment by Chocolate-lightning** [comment]
Hi Rosane,

I have found a way to implement this rather quickly. 
With the plugin we look to see if the enrolment instance has an end time if it does not then we see if the associated enrolment method does. By doing this we can see the end time of your self-enrolment instance and provide a count down and email for that date.

Hopefully this will cover what you were hoping it to.

Regards,

Matt

**Comment by rbigras** [comment]
Well, what can I say other than : so many thanks!

Does this will be included in the next upgrade of the plugin? Do you want me to try it before? We run a copy of our Moodle platform for testing purposes.

Rosane

**Comment by Chocolate-lightning** [comment]
No worries I was fixing something else at the same time.

This will be the next release of the plugin. If you tested it that would be nice otherwise it'll be fine and we'll test it in house as well.

Matt
