### ISSUE TITLE
Make the next time to alert configurable

### ISSUE THREAD

**Issue by JosiahCarberry** [learningworks/moodle-block_enrolmenttimer#5]
Once a user falls within the configured period to alert that the end of the course is coming up, that user receives an email every 24 hours. This period is not configurable, so far as I can see. Since I have set the period to 21 days (given that some users might be on vacation or otherwise unavailable), that means they receive a warning email every day for three weeks, which is probably a big annoyance. I would like to set the repeat period to 7 days, not 1 day. So, this could be done if the delay until the next time to alert were configurable.

**Comment by Chocolate-lightning** [comment]
Are you able to tell me which version this error is occurring please?

If it is the latest version I have a few thoughts as to why this may be happening.

Regards,
Matt

**Comment by JosiahCarberry** [comment]
Using plugin ver 3.3.1 (2017060900) running on moodle 3.3.1 (Build: 20170710).

I didn't realize you consider this a bug. What is the expected behavior?
Be that as it may, you might still consider making the delay configurable.

**Comment by Chocolate-lightning** [comment]
The idea was for the user to only be emailed once. 
We do this by trying to figure out when the alert time is and if it is between the previous and next cron run we fire off an email to the learner.
In your situation would you want the message to be sent every 7 days within the notice period?

Regards,
Matt

**Comment by JosiahCarberry** [comment]
OK - so there are two issues: 1) there is apparently a bug, in that the email is sent every day during the notification period, not just once; and 2) making the frequency of notification be configurable.
For me, solving 1) is pretty important; adding 2) would be nice, but of quite low priority.

**Comment by Chocolate-lightning** [comment]
I have made some changes so we now log when a email will have to be sent to a learner.
When this time passes and the message has not been sent we fire off an email and update the DB.

You can review the changes if you want on the relevant branch.
